# Generated by Django 3.2.5 on 2021-07-20 05:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.IntegerField(default=0, editable=False, help_text='Id is added automatically.')),
                ('name', models.CharField(max_length=50)),
                ('isbn', models.CharField(help_text='ISBN number is 10 or 13 digits.', max_length=13, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='length_error', message='Isbn has to be either 10 or 13 digits.', regex='(^.{10}$)|(^.{13}$)')])),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
    ]
